PUT http://localhost:8080/message/AZS2Central
Content-Type: application/json

[{"message":"авто регистрация","sender":"horol","type":"GasSalesService","payload":{"azs":"Хорол","gasolineType":"2","date":"2021-11-25T11:41:57","tank":"000000002","trk":"134","sales_type":"000900001","shift":"89","liter":"197.54","count":"197.54","price":"0.0","sum":"","customer":"Чех","check_number":"418923","manager":"","comment":" ВІ9916АІ Чех А. І.","row_number":"1","row_count":"1","extId":"fc48fa70-4dcd-11ec-af64-50465dcf48da"}}]

###

PUT http://localhost:8080/message/AZS2Central
Content-Type: application/json

[
  {
    "message": "авто регистрация",
    "sender": "test",
    "type": "GasSalesService",
    "payload": {
      "azs": "+Константы.ОсновнойСклад.Получить()",
      "gasolineType": "1",
      "date": "2021-11-25T12:59:01",
      "tank": "0",
      "trk": "1",
      "shift": "706",
      "sales_type": "0",
      "liter": "12",
      "count": "12",
      "price": "11",
      "sum": "127.00",
      "customer": "b721236a-5c7f-409d-839c-cd095665f3d8",
      "check_number": "100566",
      "extId": "9e395173-b745-4581-a593-96ea1780ab53",
      "manager": "Васян"
    }
  }
]

###

PUT http://5.9.86.71:55203/oil/message/AZS2Central
Content-Type: application/json

[
  {
    "message": "авто регистрация",
    "sender": "test-topic",
    "type": "CustomerService",
    "payload": {
      "name": "ЮРА МАЗ",
      "azs": "F001",
      "globalId": "5600c235-0050-9b30-f506-658c3dd611eb"
    }
  }
]

###

###PUT http://5.9.86.71:55203/oil/message/AZS2Central
PUT http://localhost:8080/message/AZS2Central
Content-Type: application/json


[
    {
        "message": "авто регистрация",
        "sender": "test-topic",
        "type": "GasSalesService",
        "payload": {
            "azs": "F001",
            "gasolineType": "3",
            "date": "2021-01-28T10:34:40",
            "tank": "000000005",
            "trk": "154",
            "sales_type": "000000005",
            "shift": "139",
            "liter": "0.0",
            "count": "0.0",
            "price": "0.0",
            "sum": "0.0",
            "customer": "",
            "check_number": "000000003",
            "row_number": "1",
            "row_count": "2",
            "extId": "97f16296-8df5-11eb-9b3a-00155d564e09"
        }
    },
  {
        "message": "авто регистрация",
        "sender": "test-topic",
        "type": "GasSalesService",
        "payload": {
            "azs": "F001",
            "gasolineType": "3",
            "date": "2021-01-28T10:34:40",
            "tank": "000000005",
            "trk": "154",
            "sales_type": "000000006",
            "shift": "139",
            "liter": "-32.0",
            "count": "-32.0",
            "price": "30.0",
            "sum": "-960.0",
            "customer": "",
            "check_number": "000000003",
            "row_number": "2",
            "row_count": "2",
            "extId": "97f16296-8df5-11eb-9b3a-00155d564e09"
        }
    }
]

###
PUT http://localhost:8080/message/AZS2Central
Content-Type: application/json

[
  {
    "message": "авто регистрация",
    "sender": "test-topic",
    "type": "CustomerService",
    "payload": {
      "name": "ЮРА МАЗ",
      "azs": "F001",
      "globalId": "5600c235-0050-9b30-f506-658c3dd611eb"
    }
  }
]

###
PUT http://localhost:8080/message/AZS2Central
Content-Type: application/json

[
    {
        "type": "GasSalesService",
        "message": "авто регистрация",
        "payload": {
            "gasolineType": "2",
            "date": "2021-08-25T02:02:13",
            "sales_type": "000000003",
            "shift": "205",
            "liter": "400",
            "count": "400",
            "sum": "",
            "trk": "18",
            "check_number": "279183",
            "price": "",
            "azs": "А-8",
            "extId": "72bf6c53-051e-11ec-b5e6-f02f74198dff",
            "tank": "000000004",
            "customer": "КИСИЛЁВ"
        }
    }
]

###
PUT http://localhost:8080/message/AZS2Central
Content-Type: application/json

[{"message":"авто регистрация","sender":"А5","type":"GasSalesService","payload":{"azs":"А5","gasolineType":"2","date":"2022-01-01T06:44:43","tank":"000000004","trk":"18","sales_type":"000000002","shift":"344","liter":"42","count":"42","sum":"1102.5","customer":"","check_number":"280328","price":"26.25","manager":"","comment":"  ","row_number":"1","row_count":"1","extId":"f134e795-6ad7-11ec-909f-96a257875983"}}]

###
PUT http://localhost:8080/message/AZS2Central
Content-Type: application/json

[
  {
    "message": "авто регистрация",
    "sender": "test-topic",
    "type": "GasTotalService",
    "payload": {
      "azs": "A1",
      "period": "2022-09-09T02:02:13",
      "quantity": "3754.59",
      "gasolineType": "1",
      "tank": "00006"
    }
  }
]